### ISSUE TITLE
Meridio Frontend starts attracting traffic before cluster internal connections are ready. 

### ISSUE THREAD

**Issue by tedlean** [Nordix/Meridio#470]
**Describe the bug**
When using the BGP routing protocol Meridio Frontends will announce routes for VIP-addresses as soon as the BGP session is established. This will happen despite the LB-FE is not connected internally to any proxy Pod. This way traffic is temporarily attracted into a blackhole. This is quite visible during in-service software upgrade, where the restarting of lb-fe pods causes traffic disruptions for up to 20 sec. per pod.

**To Reproduce**
1. 
2. ...

**Expected behavior**
It is probably not possible to mitigate all possible scenarios of not attracting traffic before the system is able to receive it.
E.g it could be that no target application actually is listening for the traffic in question.

Still it seems quite obvious that traffic should not be attracted into a LB-FE pod that has no internal connectivity.
The VIP-routes should only be announced then the LB-FE is connected with at least one proxy and has at least one target configured 
for the load-balancer.  

**Context**
 - Kernel: [e.g. 5.15.43]
 - Kubernetes: [e.g. v1.24.1]
 - Spire: [e.g. v1.3.0]
 - Network Service Mesh: [e.g. v1.3.1]
 - Meridio: [e.g. v0.5.1]
 ...

**Logs**
Ad

**Comment by dezenxi** [comment]
How about using netlink to monitor the interfaces (lb-proxy) or target list events in stateless-lb container?
[ip link mo](https://manpages.ubuntu.com/manpages/focal/en/man8/ip-monitor.8.html)

**Comment by LionelJouin** [comment]
As an alternative solution to #496, the frontend container can watch the VIPs via nftables instead of the NSP ConfigurationManager Service.

The load-balancer container has to configure VIPs when the service is up, so the frontend can be "aware" NFQLB is ready to handle traffic. This is currently not the case: https://github.com/Nordix/Meridio/blob/master/cmd/stateless-lb/main.go#L467

The VIPs are configured in the ipv4-vips and ipv6-vips sets of the meridio-nfqlb table of nftables. 

Advantages
- VIPs are individually advertised when they are ready to be handled by NFQLB
- No direct communication between lb and frontend containers

Drawbacks:
- Targets are not necesseraly configured (but this is user missconfiguration)
